### ISSUE TITLE
Unable to Compile

### ISSUE THREAD

**Issue by soupaboy** [jean343/RPI-GPU-rdpClient#5] opened 2016-04-21 02:00 UTC
Hi there,

Have been trying for hours trying to get this to compile by following your instructions.

I appear to be able to generate server.sln correctly with cmake but run into multiple issues when I choose to build in Visual Studio.

Currently using Visual Studio 2015 to build on. Would love to get this working as it looks amazing from the youtube video. Errors are as follows.

Severity    Code    Description Project File    Line    Suppression State
Warning C4002   too many actual parameters for macro '_T'   server  c:\pi\server\wddm.h 290 
Warning C4473   'printf' : not enough arguments passed for format string    server  c:\pi\server\wddm.h 290 
Warning C4018   '>=': signed/unsigned mismatch  server  C:\Pi\Server\server.cpp 253 
Warning C4018   '<': signed/unsigned mismatch   server  C:\Pi\Server\server.cpp 255 
Error   LNK2026 module unsafe for SAFESEH image.    server  C:\Pi\Server\Pi\avcodec.lib(dbpkbs00166.o)  1  
Error   LNK2026 module unsafe for SAFESEH image.    server  C:\Pi\Server\Pi\avcodec.lib(dbpkbs00114.o)  1  
Error   LNK2026 module unsafe for SAFESEH image.    server  C:\Pi\Server\Pi\avcodec.lib(dbpkbs00157.o)  1  
Error   LNK2026 module unsafe for SAFESEH image.    server  C:\Pi\Server\Pi\avcodec.lib(dbpkbs00116.o)  1  
Error   LNK2026 module unsafe for SAFESEH image.    server  C:\Pi\Server\Pi\avcodec.lib(dbpkbs00056.o)  1  
Error   LNK2026 module unsafe for SAFESEH image.    server  C:\Pi\Server\Pi\avcodec.lib(dbpkbs00044.o)  1  
Error   LNK2026 module unsafe for SAFESEH image.    server  C:\Pi\Server\Pi\avcodec.lib(dbpkbs00142.o)  1  
Error   LNK2026 module unsafe for SAFESEH image.    server  C:\Pi\Server\Pi\avcodec.lib(dbpkbs00134.o)  1  
Error   LNK2026 module unsafe for SAFESEH image.    server  C:\Pi\Server\Pi\avutil.lib(dhdkbs00181.o)   1  
Error   LNK2026 module unsafe for SAFESEH image.    server  C:\Pi\Server\Pi\avutil.lib(dhdkbs00182.o)   1  
Error   LNK2026 module unsafe for SAFESEH image.    server  C:\Pi\Server\Pi\avutil.lib(dhdkbs00327.o)   1  
Error   LNK2026 module unsafe for SAFESEH image.    server  C:\Pi\Server\Pi\avutil.lib(dhdkbs00141.o)   1  
Error   LNK2026 module unsafe for SAFESEH image.    server  C:\Pi\Server\Pi\avutil.lib(dhdkbs00145.o)   1  
Error   LNK2026 module unsafe for SAFESEH image.    server  C:\Pi\Server\Pi\avutil.lib(dhdkbs00244.o)   1  
Error   LNK1281 Unable to generate SAFESEH image.   server  C:\Pi\Server\Pi\Release\server.exe  1

**Comment by jean343** [comment] 2016-04-21 03:31
Hello

Searching for LNK2026 module unsafe for SAFESEH image. 
You have downloaded the wrong version of ffmpeg. Download the one for visual studio 2015

Thanks

## 

发自我的网易邮箱手机智能版

在 2016-04-21 10:00:16，soupaboy notifications@github.com 写道：

Hi there,

Have been trying for hours trying to get this to compile by following your instructions.

I appear to be able to generate server.sln correctly with cmake but run into multiple issues when I choose to build in Visual Studio.

Currently using Visual Studio 2015 to build on. Would love to get this working as it looks amazing from the youtube video. Errors are as follows.

Severity Code Description Project File Line Suppression State
Warning C4002 too many actual parameters for macro '_T' server c:\pi\server\wddm.h 290
Warning C4473 'printf' : not enough arguments passed for format string server c:\pi\server\wddm.h 290
Warning C4018 '>=': signed/unsigned mismatch server C:\Pi\Server\server.cpp 253
Warning C4018 '<': signed/unsigned mismatch server C:\Pi\Server\server.cpp 255
Error LNK2026 module unsafe for SAFESEH image. server C:\Pi\Server\Pi\avcodec.lib(dbpkbs00166.o) 1

Error LNK2026 module unsafe for SAFESEH image. server C:\Pi\Server\Pi\avcodec.lib(dbpkbs00114.o) 1

Error LNK2026 module unsafe for SAFESEH image. server C:\Pi\Server\Pi\avcodec.lib(dbpkbs00157.o) 1

Error LNK2026 module unsafe for SAFESEH image. server C:\Pi\Server\Pi\avcodec.lib(dbpkbs00116.o) 1

Error LNK2026 module unsafe for SAFESEH image. server C:\Pi\Server\Pi\avcodec.lib(dbpkbs00056.o) 1

Error LNK2026 module unsafe for SAFESEH image. server C:\Pi\Server\Pi\avcodec.lib(dbpkbs00044.o) 1

Error LNK2026 module unsafe for SAFESEH image. server C:\Pi\Server\Pi\avcodec.lib(dbpkbs00142.o) 1

Error LNK2026 module unsafe for SAFESEH image. server C:\Pi\Server\Pi\avcodec.lib(dbpkbs00134.o) 1

Error LNK2026 module unsafe for SAFESEH image. server C:\Pi\Server\Pi\avutil.lib(dhdkbs00181.o) 1

Error LNK2026 module unsafe for SAFESEH image. server C:\Pi\Server\Pi\avutil.lib(dhdkbs00182.o) 1

Error LNK2026 module unsafe for SAFESEH image. server C:\Pi\Server\Pi\avutil.lib(dhdkbs00327.o) 1

Error LNK2026 module unsafe for SAFESEH image. server C:\Pi\Server\Pi\avutil.lib(dhdkbs00141.o) 1

Error LNK2026 module unsafe for SAFESEH image. server C:\Pi\Server\Pi\avutil.lib(dhdkbs00145.o) 1

Error LNK2026 module unsafe for SAFESEH image. server C:\Pi\Server\Pi\avutil.lib(dhdkbs00244.o) 1

Error LNK1281 Unable to generate SAFESEH image. server C:\Pi\Server\Pi\Release\server.exe 1

**Comment by soupaboy** [comment] 2016-04-21 04:35
Thanks for replying so quickly. Have redownloaded x64 version of ffmpeg. Compiling throws up none of those errors but still has the 2 errors about. Wddm at the start which still cause it to fail. 

I'm running windows 10 currently so left that box ticked. I have tried unchecking wddm in cmake and rebuilding and it is a success but server and client will not connect even though it says its running. 

Do I need wddm? Or should I start troubleshooting other problems with the connection.

**Comment by jean343** [comment] 2016-04-24 20:36
What are the errors about WDDM? Can you copy your new output?

The following two lines are warning and not errors and should be OK.
Warning C4002 too many actual parameters for macro '_T' server c:\pi\server\wddm.h 290 
Warning C4473 'printf' : not enough arguments passed for format string server c:\pi\server\wddm.h 290 

If you are running Windows 10, you really should use WDDM.

Do you have an Nvidia card or are you running CPU? The FPS will be significantly lower without the GPU.

**Comment by jean343** [comment] 2018-02-13 14:12
Assuming the issue is fixed, closing for now.

**Closed as completed by jean343** 2018-02-13 14:12 UTC
