### ISSUE TITLE
Server crashes when client tries to connect

### ISSUE THREAD

**Issue by renno-bih** [jean343/RPI-GPU-rdpClient#6] opened 2018-02-12 14:03 UTC
I manage to start server, but as soon as client starts to connect server crashes. Here is what I get on server:

> C:\Users\ReNNo\Desktop\rPi Streaming\RPI-GPU-rdpClient-master\Server\build\Release>server monitor 0 port 8080
> Version 0.9
> monitor : 0
> port : 8080
> Encoding input           : "(null)"
>          output          : "(null)"
>          codec           : "H264"
>          size            : 1536x864
>          bitrate         : 1024000 bits/sec
>          vbvMaxBitrate   : 1024000 bits/sec
>          vbvSize         : 51200 bits
>          fps             : 20 frames/sec
>          rcMode          : VBR
>          goplength       : 200
>          B frames        : 0
>          QP              : 28
>        Input Format      : YUV 420
>          preset          : LOW_LATENCY_DEFAULT
>   Picture Structure      : Frame Mode
>          devicetype      : CUDA
> Output 0: [\\.\DISPLAY1] [attached] (0, 0, 1536, 864)
> Failed to get duplicate output

Here is what I get on client:

> pi@raspberrypi:/opt/vc/src/hello_pi/RPI-GPU-rdpClient/RPI-Client/build $ ./client 172.20.116.78 8080
> Version 0.9
> Open display[0]...
> Display is 1920 x 1200
> terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
>   what():  read: Connection reset by peer
> Aborted

Any idea what is causing this problem?
btw, I'm using Windows 10 on server.

Cheers,

**Comment by jean343** [comment] 2018-02-12 14:34
Hmm, this is an interesting one.
The reason is that DuplicateOutput fails, however it would be fully supported on Windows 10.
If you have time, would you mind adding a printf around https://github.com/jean343/RPI-GPU-rdpClient/blob/19b62d9bcd8d7aa04c792479344ed882e1eeec14/Server/wddm.h#L204 to show the error code returned by `status`?
I will change the code when I have a chance.
Thanks!

**Comment by renno-bih** [comment] 2018-02-12 15:07
Hi  @jean343 ,
I get this error code: 0x887a0004

EDIT:
Problem is solved now. I was using wrong DXGI path in Cmake. But now I have another problem.
Client can connect to server and I can remotely move mouse but I don't get video on raspberryPi.
Any idea?

**Comment by jean343** [comment] 2018-02-12 16:20
One thing I noticed is that you are having a different resolution in the PI and on the server.
The video should be stretched to match the PI, but the mouse coordinates are not, so the mouse won't click at the correct place if the resolutions differs.
This should not cause a blank screen though.

It seems like you are using the CPU version of encoding, is your path to FFMPEG correct? Do you have an Nividia card, it works better with it.

**Comment by renno-bih** [comment] 2018-02-13 09:55
Hi @jean343 , thanks for helping me :)

I changed resolution on Pi to 1920x1080 and they are the same but same problem is present. When rPi connects to server there is no new screen showing remote desktop.  But I cannot click on anything on my rPi, looks like something is overlaid on rPi screen but it is transparent.  (Mouse can be moved remotely)

I'm not trying to use FFMPEG for encoding, my plan is to use GTX-1050 and CUDA. 

btw, when I include same paths for DXGI as you did, server crashes  with error `0x887a0004`

**Comment by renno-bih** [comment] 2018-02-13 12:55
UPDATE:
I checked this error and found [THIS](https://support.microsoft.com/en-us/help/3019314/error-generated-when-desktop-duplication-api-capable-application-is-ru) explanation.
But after disabling integrated graphic card it **finally started working** :)

Thank you @jean343  for your support :)

**Comment by jean343** [comment] 2018-02-13 12:56
It's normal to have an overlay, we display the video as an overlay on the PI. The fact that it is transparent means that the PI does not receive video.

Would you mind sending a snapshot of the CMAKE config? I can try to reproduce with similar versions and see if it's a new library which is causing the problem.
Is there any error on the server.exe log?

**Comment by jean343** [comment] 2018-02-13 14:10
Hi,

I'm so glad you figured it, good digging!
I remember having a system with both an Intel and an Nvidia GPU, and I had to reconfigure which card is active to test the different modes.

Please let me know if it's working as expected, and I would be exited to know about your use case, we don't find GTX-1050 in all machines!!

If there are no more issues, I will close this thread.

JP

**Comment by renno-bih** [comment] 2018-02-14 09:19
Hi @jean343 , 

I don't need remote desktop functionality of this project, my goal is to make live video transmission between main PC and miniPC (rPi) where latency is not higher than 1 second.

On default settings I get latency between 133 - 200ms and that is very good, but I wish to have a little better quality video streamed on miniPC. Any tips for this?

Cheers,

**Comment by jean343** [comment] 2018-02-14 14:10
Yes, there is 1-2 frame latency, increasing the frame rate will reduce the latency. I tried hard to reduce it, but could not. I believe it's mainly caused by the encoder.

As per the video quality, you could increase the quality at the cost of bandwidth. The default is streaming on a relatively low quality.

I just realized that the version on GitHub does not take command line arguments, I will see if I can bring them.

In the meantime, you could change the fps here, try 30.
https://github.com/jean343/RPI-GPU-rdpClient/blob/master/Server/NvEncoder/NvEncoder.h#L224

You can try increasing the bitrate here
https://github.com/jean343/RPI-GPU-rdpClient/blob/master/Server/NvEncoder/NvEncoder.h#L223
try: `int B = 8 * 1000 * 1024;`

You could also reduce the qp to 20, note that a lower number leads to better quality.
`encodeConfig.qp = 20;`

Let me know which bandwidth you have, and I could fine tune those params. I still think that giving the option would be better :D

**Comment by renno-bih** [comment] 2018-02-15 08:33
I'm using it in local network and bandwidth is not an issue. 
By changing these values I got noticeable better quality :) Thank you @jean343 
There are still some artifacts on some shapes but I can live with it.

btw, you can close this thread.

**Comment by jean343** [comment] 2018-02-15 13:53
Thanks!

**Closed as completed by jean343** 2018-02-15 13:53 UTC
